<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oi" nsURI="http://www.example.org/oi" nsPrefix="oi">
  <eClassifiers xsi:type="ecore:EClass" name="ObjectInteraction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="StatesMayOnlyHaveOneTransition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="2"
        upperBound="2" eType="#//Object" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="2" upperBound="-1"
        eType="#//State" containment="true" eOpposite="#//State/container"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initiator" eSuperTypes="#//Object">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Action" eOpposite="#//Action/initiator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Responder" eSuperTypes="#//Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responder" lowerBound="1"
        eType="#//Responder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initiator" lowerBound="1"
        eType="#//Initiator" eOpposite="#//Initiator/action"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" eType="#//Transition"
        eOpposite="#//Transition/beforeState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" eType="#//Transition"
        eOpposite="#//Transition/afterState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Object" eOpposite="#//Object/state"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beforeState" lowerBound="1"
        eType="#//State" eOpposite="#//State/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterState" lowerBound="1"
        eType="#//State" eOpposite="#//State/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="transition"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="#//Object"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConnected" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Direction" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//Directions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activation" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Traversability" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTraversable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Directions">
    <eLiterals name="Left" literal="Left"/>
    <eLiterals name="Up" value="1" literal="Up"/>
    <eLiterals name="Right" value="2"/>
    <eLiterals name="Down" value="3" literal="Down"/>
  </eClassifiers>
</ecore:EPackage>
